spring:
  application:
    name: ttdo-iam
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:hzero}
    password: ${SPRING_DATASOURCE_PASSWORD:hzero}
    hikari:
      # ??????????
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      # ???????????
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # ??????????????????
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}