spring:
  application:
    name: ttdo-oauth
  datasource:
    url: ${SPRING_DATASOURCE_URL:jdbc:mysql://db.hzero.org:3306/hzero_platform?useUnicode=true&characterEncoding=utf-8&useSSL=false}
    username: ${SPRING_DATASOURCE_USERNAME:hzero}
    password: ${SPRING_DATASOURCE_PASSWORD:hzero}
    hikari:
      # 连接池最小空闲连接数
      minimum-idle: ${SPRING_DATASOURCE_MINIMUM_IDLE:20}
      # 连接池允许的最大连接数
      maximum-pool-size: ${SPRING_DATASOURCE_MAXIMUM_POOL_SIZE:200}
      # 等待连接池分配连接的最大时长（毫秒）
      connection-timeout: ${SPRING_DATASOURCE_CONNECTION_TIMEOUT:30000}
#  redis:
#    host: ${SPRING_REDIS_HOST:redis.hzero.org}
#    port: ${SPRING_REDIS_PORT:6379}
#    database: ${SPRING_REDIS_DATABASE:12}
#    lettuce:
#      pool:
#        # 资源池中最大连接数
#        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整
#        max-active: ${SPRING_REDIS_POOL_MAX_ACTIVE:50}
#        # 资源池运行最大空闲的连接数
#        # 默认8，-1表示无限制；可根据服务并发redis情况及服务端的支持上限调整，一般建议和max-active保持一致，避免资源伸缩带来的开销
#        max-idle: ${SPRING_REDIS_POOL_MAX_IDLE:50}
#        # 当资源池连接用尽后，调用者的最大等待时间(单位为毫秒)
#        # 默认 -1 表示永不超时，设置5秒
#        max-wait: ${SPRING_REDIS_POOL_MAX_WAIT:5000}
#
#y:
#  oauth:
#    # 认证服务器 自定义资源匹配器
#    custom-resource-matcher: ${HZERO_OAUTH_CUSTOM_RESOURCE_MATCHER:false}
#    # 验证 client 时不检查 client 的一致性
#    not-check-client-equals: ${HZERO_OAUTH_NOT_CHECK_CLIENT_EQUALS:false}
#    # 移动设备ID参数
#    device-id-parameter: ${HZERO_OAUTH_DEVICE_ID_PARAMETER:device_id}
#    # 登录设备来源参数
#    source-type-parameter: ${HZERO_OAUTH_SOURCE_TYPE_PARAMETER:source_type}
#    # 移动端开启图形验证码校验，默认不开启
#    enable-app-captcha: ${HZERO_OAUTH_ENABLE_APP_CAPTCHA:false}
#    # 始终开启图形验证码校验，默认否
#    enable-always-captcha: ${HZERO_OAUTH_ENABLE_ALWAYS_CAPTCHA:false}
#    # client_credentials 模式是否返回 refresh_token
#    credentials-allow-refresh: ${HZERO_OAUTH_CREDENTIALS_ALLOW_REFRESH:false}
#    # oauth 服务基础地址
#    base-url: ${HZERO_OAUTH_BASE_URL:http://127.0.0.1:28080/toauth}
#    login:
#      # 允许使用的登录名，默认有 用户名、邮箱、手机号
#      support-fields: ${HZERO_OAUTH_LOGIN_SUPPORT_FIELDS:username,email,phone}
#      # 前端默认模板
#      default-template: ${HZERO_OAUTH_LOGIN_DEFAULT_TEMPLATE:main}
#      # 跳转到默认登录成功地址时使用的客户端ID
#      default-client-id: ${HZERO_OAUTH_LOGIN_DEFAULT_CLIENT_ID:hzero-front-dev}
#      # 默认登录成功跳转地址
#      success-url: ${HZERO_OAUTH_LOGIN_SUCCESS_URL:http://127.0.0.1:8000/workplace}
#      # 密码防重放缓存过期时间，单位(天)
#      pass-replay-expire: ${HZERO_OAUTH_LOGIN_PASS_REPLAY_EXPIRE:30}
#
#hzero:
#  captcha:
#    # 是否启用验证码
#    enable: true